<a href="https://colab.research.google.com/github/ravitejagvs/The-best-classifier/blob/master/tf1_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Hello World in TensorFlow

In [1]:
# TensorFlow program to display Hello World

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf

First few important lines should be present in all Python files as per TensorFlow Style Guide:
``` python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
```

In [0]:
# Create tensor
hello = tf.string_join(["Hello, World"])

Creates a Tensor named `hello` that contains two string elements.

In [0]:
# Launch session
sess = tf.Session()

Creates a Session object named `sess`, acts as an interface to the external TensorFlow computation mechanism.

In [4]:
print(sess.run(hello))

b'Hello, World'


Launches the new Session and prints its result.

# TensorFlow Primitives

TensorFlow's central data type is the tensor.

- **Tensors** are the underlying components of computation and a fundamental data structure in TensorFlow.
- Without using complex mathematical interpretations, we can say a "*tensor (in TensorFlow) describes a multidimensional numerical array, with zero or n-dimensional collection of data, determined by rank, shape, and type.*"

A rank, shape and type are three parameters, by a tensors can be identified.

**Rank**: A tensor may have numerous dimensions, and the number of dimensions in a tensor is its rank.

**Shape**: The lengths of a tensor's dimensions form an array called the tensor's shape. In other words, the shape of a tensor is the number of rows and columns it has.
- A zero-dimensional(rank zero) tensor is called a scalar; has shape of `[1]`.
- A one-dimensional(rank one) tensor is called a vector; has shape of `[columns]` or `[rows]`.
- A two-dimensional(rank two) tensor is called a matrix; has shape of `[rows,columns]`.

**Type**: It is the data type assigned to the tensor's elements(items).

- Each tensor is an instance of the Tensor class.
- A tensor may consist of numbers, strings, floating-point or Boolean values.
- Each item or element of a tensor must have the same data type.
- Using functions of the `tf` package we can create, process, transform and operate tensors.

## Create tensors using different functions

### Create tensor using `constant` function
The `constant` function is most popular function to create tensors. The only required argument is value or list of values used to create tensor.
The default data type is `float32` is list of values are of floating type and `int32` if values are integer type.

In [0]:
t1 = tf.constant([1, 2, 3])    # one-dimensional tensor containing three integer values [data-type int32].

In [0]:
t2 = tf.constant([[1.1, 2.2, 3.3], [4, 5, 6]])     # t2 is a two-dimensional tensor containing floating-point values [data-type float32].

In [0]:
t3 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # two-dimensional tensor

In [0]:
t4 = tf.constant(["India", "Germany"])          # one-dimensional tensor with strings

In [0]:
t5 = tf.constant([15.5, 20.5, 35.5, 40.1, 80.5], tf.float16, [5], 'T5', False)

We have specified `data-type` as `float16`; `name` as `T5`; and `shape` as `6`. Note If we will pass more than 6 elements it will throw an error 
```python
Too many elements provided. Needed at most 6, but received 7
```

In [0]:
sess = tf.Session()

In [11]:
print(t1)

Tensor("Const:0", shape=(3,), dtype=int32)


In [12]:
print(t2)

Tensor("Const_1:0", shape=(2, 3), dtype=float32)


In [13]:
print(t3)

Tensor("Const_2:0", shape=(3, 3), dtype=int32)


In [14]:
print(sess.run(t3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(t4)

Tensor("Const_3:0", shape=(2,), dtype=string)


In [16]:
print(sess.run(t4))

[b'India' b'Germany']


In [17]:
print(t5)

Tensor("T5:0", shape=(5,), dtype=float16)


In [18]:
print(sess.run(t5))

[15.5 20.5 35.5 40.1 80.5]


### Create tensor using `zeros` function
The function `zeros` create tensors with all elements set to zero and the only required argument of function is shape of tensor.

In [0]:
zero_tensor = tf.zeros([3])                 # shape 3 tensor

In [0]:
print(zero_tensor)

Tensor("zeros:0", shape=(3,), dtype=float32)


In [0]:
zero_tensor_int = tf.zeros([3], tf.int32, 'ZeroTensor')

In [0]:
print(zero_tensor_int)                  # name: ZeroTensor, shape: 3

Tensor("ZeroTensor_1:0", shape=(3,), dtype=int32)


In [0]:
zero_tensor_4x_4x_4x = tf.zeros([4, 4, 4], tf.int8, '4X-ZeroTensor')    # d-type: int-8

In [0]:
print(zero_tensor_4x_4x_4x)

Tensor("4X-ZeroTensor:0", shape=(4, 4, 4), dtype=int8)


In [0]:
sess = tf.Session()
print(sess.run(zero_tensor_4x_4x_4x))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


### Create tensor using `ones` function
The function `ones` also create tensors with all elements set to one and the only required argument of function is `shape` of tensor.

In [0]:
one_tensor = tf.ones([3])                  # shape: 3

In [0]:
print(one_tensor)

Tensor("ones:0", shape=(3,), dtype=float32)


In [0]:
one_tensor_int = tf.ones([2, 2], tf.complex64, 'Complex-OneTensor')      # name: Complex-OneTensor, shape: 2x2, d-type: complex64

In [0]:
print(one_tensor_int)

Tensor("Complex-OneTensor:0", shape=(2, 2), dtype=complex64)


In [0]:
one_tensor_4x_4x_4x = tf.ones([4, 4, 4], tf.int8, '4X-ZeroTensor')       # name: 4X-ZeroTensor, shape: 4x4x4, d-type: int8

In [0]:
sess = tf.Session()

In [0]:
print(sess.run(one_tensor_4x_4x_4x))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


### Create tensor using `fill` function
The function `fill` creates tensors with all elements having same value to pass in an argument. Data-type of tensor depends upon value passed in argument.

In [0]:
fill_tensor = tf.fill([3], 10)             # shape: 3, all-values: 10

In [0]:
print(fill_tensor)

Tensor("Fill:0", shape=(3,), dtype=int32)


In [0]:
sess = tf.Session()

In [0]:
print(sess.run(fill_tensor))

[10 10 10]


In [0]:
fill_tensor_2x_2x = tf.fill([2, 2], 15, '2x-Fill-Tensor')              # shape: 2x2, all-values: 15, name: 2x-Fill-Tensor

In [0]:
print(fill_tensor_2x_2x)

In [0]:
print(sess.run(fill_tensor_2x_2x))

In [0]:
fill_tensor_string = tf.fill([2, 2], "Japan", 'String-Fill-Tensor')    # shape: 2x2, all-values: 'Japan', name: String-Fill-Tensor

In [0]:
print(fill_tensor_string)

In [0]:
print(sess.run(fill_tensor_string))

In [0]:
fill_tensor_4x_4x_4x = tf.fill([4, 4, 4], 10.15, '4X-Fill-Tensor')     # shape: 4x4x4, all-vlaues: 10.15, name: 4X-Fill-Tensor

In [0]:
print(fill_tensor_4x_4x_4x)

In [0]:
print(sess.run(fill_tensor_4x_4x_4x))

### Create tensor using `linspace` function

In [0]:
linspace_tensor = tf.linspace(5.0, 10.0, 5, "Linspace-Tensor")          # name: Linspace-Tensor, values: 5-10 with 5 equally divided elements

In [0]:
print(linspace_tensor)

In [0]:
sess = tf.Session()

In [0]:
print(sess.run(linspace_tensor))

In [0]:
linspace_tensor_dec = tf.linspace(100.0, 20.0, 20, "Linspace-Tensor-Down")  # name: Linspace-Tensor-Down, values: 100-20 with equally space 20 values

In [0]:
print(linspace_tensor_dec)

In [0]:
print(sess.run(linspace_tensor_dec))

### Create tensor using `range` function
The `range` functions create tensors without accepting number of elements, however it computes successive elements by adding a value called `delta`.

In [0]:
range_tensor = tf.range(20.0, 100.0, delta=15.5)                         # 20-100 with an increment of 15.5

In [0]:
print(range_tensor)

In [0]:
sess = tf.Session()

In [0]:
print(sess.run(range_tensor))

In [0]:
range_tensor_delta = tf.range(100.0, delta=15.5, name="Range-Tensor")    # name: Range-Tensor, values: 0-100 with an increment of 15.5

In [0]:
print(range_tensor_delta)

In [0]:
print(sess.run(range_tensor_delta))

### Creating tensors with random values
The `random_normal` function creates a tensor with `normal`ly distributed values.

The `random_uniform` function creates a tensor with `uniform`ly distributed values between the minimum and maximum values.

In [0]:
random_normal_tensor = tf.random_normal([10], mean=1.0, stddev=2.0,
                                        dtype=tf.float64, name="RNT")          # normal distribution with maen=1 & standard deviation=2

In [0]:
print(random_normal_tensor)

In [0]:
sess = tf.Session()

In [0]:
print(sess.run(random_normal_tensor))

In [0]:
random_uniform_tensor = tf.random_uniform([10], minval=0.0, maxval=5.0,
                                          dtype=tf.float64, name="RUT")        # uniform distribution with minimum 0 and maximun 5

In [0]:
print(random_uniform_tensor)

In [0]:
print(sess.run(random_uniform_tensor))

## Transforming tensors using different functions

### Reshape a tensor
The function `reshape` used to change the shape of a tensor with same element and data-type.

In [0]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])          # two-dimensional tensor with shape 2x3

In [0]:
print(t1)

In [0]:
sess = tf.Session()

In [0]:
print(sess.run(t1))

In [0]:
r1 = tf.reshape(t1, [3, 2])                       # reshaping t1 to 3x2 tensor

In [0]:
print(r1)

In [0]:
print(sess.run(r1))

In [0]:
t2 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8])        # one-dimensional tensor with shape 1x8

In [0]:
print(t2)

In [0]:
print(sess.run(t2))

In [0]:
r2 = tf.reshape(t2, [4, 2])                       # reshaping it to 4x2 tensor

In [0]:
print(r2)

In [0]:
print(sess.run(r2))

### Change data type of tensor
The `cast` function used to change the data-type of tensor.

In [0]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])             # 2-d tensor with shape 2x3 and default dtype:int32

In [0]:
print(t1)

In [0]:
c1 = tf.cast(t1, dtype=tf.float16)                   # changing t1 to float16

In [0]:
print(c1)

In [0]:
t2 = tf.constant([1.2, 2, 3, 4, 5, 6, 7, 8])         # 1-d tensor with shape 1x8 and dtype:float32

In [0]:
print(t2)

In [0]:
c2 = tf.cast(t2, dtype=tf.int32)                     # changing t2 to int32

In [0]:
print(c2)

### Reverse a tensor
The `reverse` function reverses given dimensions of the tensor.

In [0]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])     # 2-d tensor with shape 3x3

In [0]:
sess = tf.Session()

In [0]:
print(sess.run(t1))

In [0]:
r1 = tf.reverse(t1, [0])                                # reverse the tensor row-wise

In [0]:
print(sess.run(r1))

In [0]:
r2 = tf.reverse(t1, [0, 1])                             # reverse the tensor both row & column wise

In [0]:
print(sess.run(r2))

In [0]:
r3 = tf.reverse(t1, [1])                               # reverse the tensor column-wise

In [0]:
print(sess.run(r3))

### Slice a tensor
The `slice` function extracts sub-tensors from a tensor.
```python
t = tf.constant([[[1, 1, 1], [2, 2, 2]],
                 [[3, 3, 3], [4, 4, 4]],
                 [[5, 5, 5], [6, 6, 6]]])
```
The first array is the first dimension, `t = [[A], [B], [C]]`<br>
The second dimension, `A = [i, j], B = [k, l], C = [m, n]`<br>
The third dimension `i = [1, 1, 1], j = [2, 2, 2], k = [3, 3 ,3], l = [4, 4, 4], m = [5, 5, 5], n = [6, 6, 6]`

`tf.slice(t, [1, 0, 0], [1, 1, 3]) ` gives `[[[3, 3, 3]]]`<br>
`tf.slice(input_`, `begin`, `size)`

`begin`s with `[B]` (`1`), `0` in second dimension and `0` in third dimension.

In `size`, we take `[B]` i.e., (`1`), then in `[B]`, we only take one value from the starting point, which value is `[k]`. Then in `[k]`, we take three value from the starting point which value is `[3, 3, 3]`. Combined, the output of the function is `[[[3, 3, 3]]]`.

In [0]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])      # 2-D tensor with shape 3x3

In [0]:
sess = tf.Session()

In [0]:
print(sess.run(t1))

In [0]:
s1 = tf.slice(t1, [1, 1], [1,1])                         # accessing 2nd row, 2nd element with size 1x1

In [0]:
print(sess.run(s1))

In [0]:
s2 = tf.slice(t1, [1, 1], [2, 2])                        # accessing 2nd row-2nd element with size 2x2

In [0]:
print(sess.run(s2))

In [0]:
s3 = tf.slice(t1, [1, 2], [2, 1])                        # accessing 2nd row-3rd element with size 2x1

In [0]:
print(sess.run(s3))

## TensorFlow Conditionals & Loops

### `tf.cond`: Simple Lambdas
Here we have two constant tensors `t1` and `t2` and we execute either `f1()` or `f2()` based on the result of `tf.less()` operation:

In [0]:
t1 = tf.constant(1)
t2 = tf.constant(2)

def f1(): return t1+t2
def f2(): return t1-t2

res = tf.cond(tf.less(t1, t2), f1, f2)

with tf.Session() as sess:
    print(sess.run(res))

As expected the printed number is `3` since `1 < 2` and thus the `f1()` gets executed. It’s worth noting that both lambdas here are single line functions, neither of which accepts any parameters.

### `tf.while_loop`: Basics
We have two constant tensors `t1` and `t2` and we will run a loop that will be incrementing `t1` while it’s less than `t2`:

In [0]:
def cond(t1, t2):
    return tf.less(t1, t2)

def body(t1, t2):
    return [tf.add(t1, 1), t2]

t1 = tf.constant(1)
t2 = tf.constant(5)

res = tf.while_loop(cond, body, [t1, t2])

with tf.Session() as sess:
    print(sess.run(res))

This result makes perfect sense: we keep incrementing the original value (`1`) until it’s less than `5`. Once it reaches `5` the `tf.while_loop` stops and the last value returned by `body` is returned as a result.